export const GENERATE_MAP = 'GENERATE_MAP'
export const MOVE = 'MOVE'
export const CHANGE_PLAYER = 'CHANGE_PLAYER'
export const SET_END_GAME = 'SET_END_GAME'
export const SET_WIN_COORDS = 'SET_WIN_COORDS'
